// This file is automatically generated by scripts/generateImageList.js
// Do not edit this file manually.

import img_0 from "../public/images/1-2/감송향.jpeg";
import img_1 from "../public/images/1-2/감수.jpeg";
import img_2 from "../public/images/1-2/건강.jpeg";
import img_3 from "../public/images/1-2/견우자.jpeg";
import img_4 from "../public/images/1-2/고량강.jpeg";
import img_5 from "../public/images/1-2/곡기생.jpeg";
import img_6 from "../public/images/1-2/광곽향.jpeg";
import img_7 from "../public/images/1-2/구맥.jpeg";
import img_8 from "../public/images/1-2/금은화.jpeg";
import img_9 from "../public/images/1-2/금전백화사.jpeg";
import img_10 from "../public/images/1-2/금전초.jpeg";
import img_11 from "../public/images/1-2/낙석등.jpeg";
import img_12 from "../public/images/1-2/노회.jpeg";
import img_13 from "../public/images/1-2/녹두.jpeg";
import img_14 from "../public/images/1-2/누로.jpeg";
import img_15 from "../public/images/1-2/단향.jpeg";
import img_16 from "../public/images/1-2/대극.jpeg";
import img_17 from "../public/images/1-2/대복피.jpeg";
import img_18 from "../public/images/1-2/대청엽.jpeg";
import img_19 from "../public/images/1-2/대황.jpeg";
import img_20 from "../public/images/1-2/독활.jpeg";
import img_21 from "../public/images/1-2/동과피.jpeg";
import img_22 from "../public/images/1-2/동규자.jpeg";
import img_23 from "../public/images/1-2/등심초.jpeg";
import img_24 from "../public/images/1-2/마전자.jpeg";
import img_25 from "../public/images/1-2/마치현.jpeg";
import img_26 from "../public/images/1-2/망초.jpeg";
import img_27 from "../public/images/1-2/매괴화.jpeg";
import img_28 from "../public/images/1-2/목과.jpeg";
import img_29 from "../public/images/1-2/목통.jpeg";
import img_30 from "../public/images/1-2/목향.jpeg";
import img_31 from "../public/images/1-2/반변련.jpeg";
import img_32 from "../public/images/1-2/발계.jpeg";
import img_33 from "../public/images/1-2/방기.jpeg";
import img_34 from "../public/images/1-2/백두구.jpeg";
import img_35 from "../public/images/1-2/백두옹.jpeg";
import img_36 from "../public/images/1-2/백렴.jpeg";
import img_37 from "../public/images/1-2/백미.jpeg";
import img_38 from "../public/images/1-2/백화사설초.jpeg";
import img_39 from "../public/images/1-2/복령.jpeg";
import img_40 from "../public/images/1-2/부자.jpeg";
import img_41 from "../public/images/1-2/비해.jpeg";
import img_42 from "../public/images/1-2/사간.jpeg";
import img_43 from "../public/images/1-2/사인.jpeg";
import img_44 from "../public/images/1-2/산두근.jpeg";
import img_45 from "../public/images/1-2/산자고.jpeg";
import img_46 from "../public/images/1-2/삼백초.jpeg";
import img_47 from "../public/images/1-2/상기생.jpeg";
import img_48 from "../public/images/1-2/상륙.jpeg";
import img_49 from "../public/images/1-2/상지.jpeg";
import img_50 from "../public/images/1-2/석위.jpeg";
import img_51 from "../public/images/1-2/소회향.jpeg";
import img_52 from "../public/images/1-2/속수자.jpeg";
import img_53 from "../public/images/1-2/시체.jpeg";
import img_54 from "../public/images/1-2/야국화.jpeg";
import img_55 from "../public/images/1-2/어성초.jpeg";
import img_56 from "../public/images/1-2/여지핵.jpeg";
import img_57 from "../public/images/1-2/연교.jpeg";
import img_58 from "../public/images/1-2/오가피.jpeg";
import img_59 from "../public/images/1-2/오수유.jpeg";
import img_60 from "../public/images/1-2/오약.jpeg";
import img_61 from "../public/images/1-2/옥미수.jpeg";
import img_62 from "../public/images/1-2/우황.jpeg";
import img_63 from "../public/images/1-2/욱리인.jpeg";
import img_64 from "../public/images/1-2/웅담.jpeg";
import img_65 from "../public/images/1-2/원화.jpeg";
import img_66 from "../public/images/1-2/위령선.jpeg";
import img_67 from "../public/images/1-2/위릉채.jpeg";
import img_68 from "../public/images/1-2/육계.jpeg";
import img_69 from "../public/images/1-2/은시호.jpeg";
import img_70 from "../public/images/1-2/의이인.jpeg";
import img_71 from "../public/images/1-2/인동등.jpeg";
import img_72 from "../public/images/1-2/인진호.jpeg";
import img_73 from "../public/images/1-2/자화지정.jpeg";
import img_74 from "../public/images/1-2/잠사.jpeg";
import img_75 from "../public/images/1-2/저령.jpeg";
import img_76 from "../public/images/1-2/적소두.jpeg";
import img_77 from "../public/images/1-2/정향.jpeg";
import img_78 from "../public/images/1-2/조휴.jpeg";
import img_79 from "../public/images/1-2/지각.jpeg";
import img_80 from "../public/images/1-2/지골피.jpeg";
import img_81 from "../public/images/1-2/지부자.jpeg";
import img_82 from "../public/images/1-2/지실.jpeg";
import img_83 from "../public/images/1-2/진교.jpeg";
import img_84 from "../public/images/1-2/진피.jpeg";
import img_85 from "../public/images/1-2/진피2.jpeg";
import img_86 from "../public/images/1-2/차전자.jpeg";
import img_87 from "../public/images/1-2/창출.jpeg";
import img_88 from "../public/images/1-2/천련자.jpeg";
import img_89 from "../public/images/1-2/천오두.jpeg";
import img_90 from "../public/images/1-2/청대.jpeg";
import img_91 from "../public/images/1-2/청목향.jpeg";
import img_92 from "../public/images/1-2/청피.jpeg";
import img_93 from "../public/images/1-2/청호.jpeg";
import img_94 from "../public/images/1-2/초과.jpeg";
import img_95 from "../public/images/1-2/초두구.jpeg";
import img_96 from "../public/images/1-2/초오.jpeg";
import img_97 from "../public/images/1-2/촉초.jpeg";
import img_98 from "../public/images/1-2/취오동.jpeg";
import img_99 from "../public/images/1-2/침향.jpeg";
import img_100 from "../public/images/1-2/택사.jpeg";
import img_101 from "../public/images/1-2/토목향.jpeg";
import img_102 from "../public/images/1-2/토복령.jpeg";
import img_103 from "../public/images/1-2/파두.jpeg";
import img_104 from "../public/images/1-2/판람근.jpeg";
import img_105 from "../public/images/1-2/패란.jpeg";
import img_106 from "../public/images/1-2/패장.jpeg";
import img_107 from "../public/images/1-2/편축.jpeg";
import img_108 from "../public/images/1-2/포공영.jpeg";
import img_109 from "../public/images/1-2/필발.jpeg";
import img_110 from "../public/images/1-2/필징가.jpeg";
import img_111 from "../public/images/1-2/해금사.jpeg";
import img_112 from "../public/images/1-2/해동피.jpeg";
import img_113 from "../public/images/1-2/해백.jpeg";
import img_114 from "../public/images/1-2/향부자.jpeg";
import img_115 from "../public/images/1-2/호초.jpeg";
import img_116 from "../public/images/1-2/호황련.jpeg";
import img_117 from "../public/images/1-2/화마인.jpeg";
import img_118 from "../public/images/1-2/활석.jpeg";
import img_119 from "../public/images/1-2/후박.jpeg";
import img_120 from "../public/images/1-2/희렴초.jpeg";
import img_121 from "../public/images/2-1/강황.jpeg";
import img_122 from "../public/images/2-1/건칠.jpeg";
import img_123 from "../public/images/2-1/계내금.jpeg";
import img_124 from "../public/images/2-1/계혈등.jpeg";
import img_125 from "../public/images/2-1/고련피.jpeg";
import img_126 from "../public/images/2-1/곡아.jpeg";
import img_127 from "../public/images/2-1/곤포.jpeg";
import img_128 from "../public/images/2-1/과루.jpeg";
import img_129 from "../public/images/2-1/관동화.jpeg";
import img_130 from "../public/images/2-1/관중.jpeg";
import img_131 from "../public/images/2-1/괴화.jpeg";
import img_132 from "../public/images/2-1/권백.jpeg";
import img_133 from "../public/images/2-1/길경.jpeg";
import img_134 from "../public/images/2-1/내복자.jpeg";
import img_135 from "../public/images/2-1/뇌환.jpeg";
import img_136 from "../public/images/2-1/능소화.jpeg";
import img_137 from "../public/images/2-1/단삼.jpeg";
import img_138 from "../public/images/2-1/대계.jpeg";
import img_139 from "../public/images/2-1/도인.jpeg";
import img_140 from "../public/images/2-1/동과자.jpeg";
import img_141 from "../public/images/2-1/마두령.jpeg";
import img_142 from "../public/images/2-1/맥아.jpeg";
import img_143 from "../public/images/2-1/몰약.jpeg";
import img_144 from "../public/images/2-1/무이.jpeg";
import img_145 from "../public/images/2-1/반대해.jpeg";
import img_146 from "../public/images/2-1/반하.jpeg";
import img_147 from "../public/images/2-1/백개자.jpeg";
import img_148 from "../public/images/2-1/백과.jpeg";
import img_149 from "../public/images/2-1/백급.jpeg";
import img_150 from "../public/images/2-1/백모근.jpeg";
import img_151 from "../public/images/2-1/백부근.jpeg";
import img_152 from "../public/images/2-1/백부자.jpeg";
import img_153 from "../public/images/2-1/백자인.jpeg";
import img_154 from "../public/images/2-1/백전.jpeg";
import img_155 from "../public/images/2-1/비자.jpeg";
import img_156 from "../public/images/2-1/비파엽.jpeg";
import img_157 from "../public/images/2-1/빈랑자.jpeg";
import img_158 from "../public/images/2-1/사군자.jpeg";
import img_159 from "../public/images/2-1/산사.jpeg";
import img_160 from "../public/images/2-1/산조인.jpeg";
import img_161 from "../public/images/2-1/삼릉.jpeg";
import img_162 from "../public/images/2-1/삼칠.jpeg";
import img_163 from "../public/images/2-1/상백피.jpeg";
import img_164 from "../public/images/2-1/선복화.jpeg";
import img_165 from "../public/images/2-1/소계.jpeg";
import img_166 from "../public/images/2-1/소목.jpeg";
import img_167 from "../public/images/2-1/소자.jpeg";
import img_168 from "../public/images/2-1/수질.jpeg";
import img_169 from "../public/images/2-1/신곡.jpeg";
import img_170 from "../public/images/2-1/아출.jpeg";
import img_171 from "../public/images/2-1/애엽.jpeg";
import img_172 from "../public/images/2-1/야교등.jpeg";
import img_173 from "../public/images/2-1/양제근.jpeg";
import img_174 from "../public/images/2-1/영지.jpeg";
import img_175 from "../public/images/2-1/오령지.jpeg";
import img_176 from "../public/images/2-1/왕불류행.jpeg";
import img_177 from "../public/images/2-1/용골.jpeg";
import img_178 from "../public/images/2-1/용아초.jpeg";
import img_179 from "../public/images/2-1/우슬.jpeg";
import img_180 from "../public/images/2-1/우절.jpeg";
import img_181 from "../public/images/2-1/울금.jpeg";
import img_182 from "../public/images/2-1/원지.jpeg";
import img_183 from "../public/images/2-1/유향.jpeg";
import img_184 from "../public/images/2-1/익모초.jpeg";
import img_185 from "../public/images/2-1/자석.jpeg";
import img_186 from "../public/images/2-1/자연동.jpeg";
import img_187 from "../public/images/2-1/자완.jpeg";
import img_188 from "../public/images/2-1/자충.jpeg";
import img_189 from "../public/images/2-1/전호.jpeg";
import img_190 from "../public/images/2-1/절패모.jpeg";
import img_191 from "../public/images/2-1/정력자.jpeg";
import img_192 from "../public/images/2-1/조각자.jpeg";
import img_193 from "../public/images/2-1/조협.jpeg";
import img_194 from "../public/images/2-1/종려피.jpeg";
import img_195 from "../public/images/2-1/주사.jpeg";
import img_196 from "../public/images/2-1/죽력.jpeg";
import img_197 from "../public/images/2-1/죽여.jpeg";
import img_198 from "../public/images/2-1/지유.jpeg";
import img_199 from "../public/images/2-1/천궁.jpeg";
import img_200 from "../public/images/2-1/천남성.jpeg";
import img_201 from "../public/images/2-1/천산갑.jpeg";
import img_202 from "../public/images/2-1/천축황.jpeg";
import img_203 from "../public/images/2-1/천패모.jpeg";
import img_204 from "../public/images/2-1/청몽석.jpeg";
import img_205 from "../public/images/2-1/충위자, 충울자.jpeg";
import img_206 from "../public/images/2-1/측백엽.jpeg";
import img_207 from "../public/images/2-1/택란.jpeg";
import img_208 from "../public/images/2-1/포황.jpeg";
import img_209 from "../public/images/2-1/학슬.jpeg";
import img_210 from "../public/images/2-1/합환피.jpeg";
import img_211 from "../public/images/2-1/해조.jpeg";
import img_212 from "../public/images/2-1/행인.jpeg";
import img_213 from "../public/images/2-1/현호색.jpeg";
import img_214 from "../public/images/2-1/혈갈.jpeg";
import img_215 from "../public/images/2-1/호박.jpeg";
import img_216 from "../public/images/2-1/호장근.jpeg";
import img_217 from "../public/images/2-1/홍화.jpeg";
import img_218 from "../public/images/2-2/가자.jpeg";
import img_219 from "../public/images/2-2/감초.jpeg";
import img_220 from "../public/images/2-2/검실.jpeg";
import img_221 from "../public/images/2-2/결명자.jpeg";
import img_222 from "../public/images/2-2/경분.jpeg";
import img_223 from "../public/images/2-2/골쇄보.jpeg";
import img_224 from "../public/images/2-2/과체.jpeg";
import img_225 from "../public/images/2-2/구기자.jpeg";
import img_226 from "../public/images/2-2/구인.jpeg";
import img_227 from "../public/images/2-2/구자.jpeg";
import img_228 from "../public/images/2-2/구척.jpeg";
import img_229 from "../public/images/2-2/구판.jpeg";
import img_230 from "../public/images/2-2/금앵자.jpeg";
import img_231 from "../public/images/2-2/나도근.jpeg";
import img_232 from "../public/images/2-2/노감석.jpeg";
import img_233 from "../public/images/2-2/노봉방.jpeg";
import img_234 from "../public/images/2-2/녹각.jpeg";
import img_235 from "../public/images/2-2/녹각교.jpeg";
import img_236 from "../public/images/2-2/녹각상.jpeg";
import img_237 from "../public/images/2-2/녹용.jpeg";
import img_238 from "../public/images/2-2/담반.jpeg";
import img_239 from "../public/images/2-2/당귀.jpeg";
import img_240 from "../public/images/2-2/당삼.jpeg";
import img_241 from "../public/images/2-2/대자석.jpeg";
import img_242 from "../public/images/2-2/대조.jpeg";
import img_243 from "../public/images/2-2/대풍자.jpeg";
import img_244 from "../public/images/2-2/동충화초.jpeg";
import img_245 from "../public/images/2-2/두충.jpeg";
import img_246 from "../public/images/2-2/마황근.jpeg";
import img_247 from "../public/images/2-2/맥문동.jpeg";
import img_248 from "../public/images/2-2/모려.jpeg";
import img_249 from "../public/images/2-2/목근피.jpeg";
import img_250 from "../public/images/2-2/반묘.jpeg";
import img_251 from "../public/images/2-2/백강잠.jpeg";
import img_252 from "../public/images/2-2/백반.jpeg";
import img_253 from "../public/images/2-2/백작약.jpeg";
import img_254 from "../public/images/2-2/백질려.jpeg";
import img_255 from "../public/images/2-2/백출.jpeg";
import img_256 from "../public/images/2-2/백편두.jpeg";
import img_257 from "../public/images/2-2/백합.jpeg";
import img_258 from "../public/images/2-2/별갑.jpeg";
import img_259 from "../public/images/2-2/보골지.jpeg";
import img_260 from "../public/images/2-2/복분자.jpeg";
import img_261 from "../public/images/2-2/봉밀.jpeg";
import img_262 from "../public/images/2-2/부소맥.jpeg";
import img_263 from "../public/images/2-2/붕사.jpeg";
import img_264 from "../public/images/2-2/비석.jpeg";
import img_265 from "../public/images/2-2/빙편.jpeg";
import img_266 from "../public/images/2-2/사삼.jpeg";
import img_267 from "../public/images/2-2/사상자.jpeg";
import img_268 from "../public/images/2-2/사원질려.jpeg";
import img_269 from "../public/images/2-2/사향.jpeg";
import img_270 from "../public/images/2-2/산수유.jpeg";
import img_271 from "../public/images/2-2/산약.jpeg";
import img_272 from "../public/images/2-2/상산.jpeg";
import img_273 from "../public/images/2-2/상심자.jpeg";
import img_274 from "../public/images/2-2/상표초.jpeg";
import img_275 from "../public/images/2-2/석결명.jpeg";
import img_276 from "../public/images/2-2/석곡.jpeg";
import img_277 from "../public/images/2-2/석류피.jpeg";
import img_278 from "../public/images/2-2/석창포.jpeg";
import img_279 from "../public/images/2-2/선모.jpeg";
import img_280 from "../public/images/2-2/섬수.jpeg";
import img_281 from "../public/images/2-2/소합향.jpeg";
import img_282 from "../public/images/2-2/속단.jpeg";
import img_283 from "../public/images/2-2/쇄양.jpeg";
import img_284 from "../public/images/2-2/숙지황.jpeg";
import img_285 from "../public/images/2-2/아교.jpeg";
import img_286 from "../public/images/2-2/안식향.jpeg";
import img_287 from "../public/images/2-2/양기석.jpeg";
import img_288 from "../public/images/2-2/여로.jpeg";
import img_289 from "../public/images/2-2/여정자.jpeg";
import img_290 from "../public/images/2-2/연자육.jpeg";
import img_291 from "../public/images/2-2/연탄.jpeg";
import img_292 from "../public/images/2-2/영양각.jpeg";
import img_293 from "../public/images/2-2/오공.jpeg";
import img_294 from "../public/images/2-2/오매.jpeg";
import img_295 from "../public/images/2-2/오미자.jpeg";
import img_296 from "../public/images/2-2/오배자.jpeg";
import img_297 from "../public/images/2-2/옥죽.jpeg";
import img_298 from "../public/images/2-2/용안육.jpeg";
import img_299 from "../public/images/2-2/우여량.jpeg";
import img_300 from "../public/images/2-2/웅황.jpeg";
import img_301 from "../public/images/2-2/유황.jpeg";
import img_302 from "../public/images/2-2/육두구.jpeg";
import img_303 from "../public/images/2-2/육종용.jpeg";
import img_304 from "../public/images/2-2/음양곽.jpeg";
import img_305 from "../public/images/2-2/익지인.jpeg";
import img_306 from "../public/images/2-2/인삼.jpeg";
import img_307 from "../public/images/2-2/자하거.jpeg";
import img_308 from "../public/images/2-2/장뇌.jpeg";
import img_309 from "../public/images/2-2/저실자.jpeg";
import img_310 from "../public/images/2-2/적석지.jpeg";
import img_311 from "../public/images/2-2/전갈.jpeg";
import img_312 from "../public/images/2-2/조구등.jpeg";
import img_313 from "../public/images/2-2/진주.jpeg";
import img_314 from "../public/images/2-2/천마.jpeg";
import img_315 from "../public/images/2-2/천문동.jpeg";
import img_316 from "../public/images/2-2/춘피.jpeg";
import img_317 from "../public/images/2-2/토사자.jpeg";
import img_318 from "../public/images/2-2/파극천.jpeg";
import img_319 from "../public/images/2-2/하수오.jpeg";
import img_320 from "../public/images/2-2/한련초.jpeg";
import img_321 from "../public/images/2-2/합개.jpeg";
import img_322 from "../public/images/2-2/해구신.jpeg";
import img_323 from "../public/images/2-2/해마.jpeg";
import img_324 from "../public/images/2-2/해표초.jpeg";
import img_325 from "../public/images/2-2/호도인.jpeg";
import img_326 from "../public/images/2-2/호로퍄.jpeg";
import img_327 from "../public/images/2-2/황기.jpeg";
import img_328 from "../public/images/2-2/황정.jpeg";
import img_329 from "../public/images/2-2/흑지마.jpeg";

export const imageMap: Record<string, any> = {
  "1-2/감송향.jpeg": img_0,
  "1-2/감수.jpeg": img_1,
  "1-2/건강.jpeg": img_2,
  "1-2/견우자.jpeg": img_3,
  "1-2/고량강.jpeg": img_4,
  "1-2/곡기생.jpeg": img_5,
  "1-2/광곽향.jpeg": img_6,
  "1-2/구맥.jpeg": img_7,
  "1-2/금은화.jpeg": img_8,
  "1-2/금전백화사.jpeg": img_9,
  "1-2/금전초.jpeg": img_10,
  "1-2/낙석등.jpeg": img_11,
  "1-2/노회.jpeg": img_12,
  "1-2/녹두.jpeg": img_13,
  "1-2/누로.jpeg": img_14,
  "1-2/단향.jpeg": img_15,
  "1-2/대극.jpeg": img_16,
  "1-2/대복피.jpeg": img_17,
  "1-2/대청엽.jpeg": img_18,
  "1-2/대황.jpeg": img_19,
  "1-2/독활.jpeg": img_20,
  "1-2/동과피.jpeg": img_21,
  "1-2/동규자.jpeg": img_22,
  "1-2/등심초.jpeg": img_23,
  "1-2/마전자.jpeg": img_24,
  "1-2/마치현.jpeg": img_25,
  "1-2/망초.jpeg": img_26,
  "1-2/매괴화.jpeg": img_27,
  "1-2/목과.jpeg": img_28,
  "1-2/목통.jpeg": img_29,
  "1-2/목향.jpeg": img_30,
  "1-2/반변련.jpeg": img_31,
  "1-2/발계.jpeg": img_32,
  "1-2/방기.jpeg": img_33,
  "1-2/백두구.jpeg": img_34,
  "1-2/백두옹.jpeg": img_35,
  "1-2/백렴.jpeg": img_36,
  "1-2/백미.jpeg": img_37,
  "1-2/백화사설초.jpeg": img_38,
  "1-2/복령.jpeg": img_39,
  "1-2/부자.jpeg": img_40,
  "1-2/비해.jpeg": img_41,
  "1-2/사간.jpeg": img_42,
  "1-2/사인.jpeg": img_43,
  "1-2/산두근.jpeg": img_44,
  "1-2/산자고.jpeg": img_45,
  "1-2/삼백초.jpeg": img_46,
  "1-2/상기생.jpeg": img_47,
  "1-2/상륙.jpeg": img_48,
  "1-2/상지.jpeg": img_49,
  "1-2/석위.jpeg": img_50,
  "1-2/소회향.jpeg": img_51,
  "1-2/속수자.jpeg": img_52,
  "1-2/시체.jpeg": img_53,
  "1-2/야국화.jpeg": img_54,
  "1-2/어성초.jpeg": img_55,
  "1-2/여지핵.jpeg": img_56,
  "1-2/연교.jpeg": img_57,
  "1-2/오가피.jpeg": img_58,
  "1-2/오수유.jpeg": img_59,
  "1-2/오약.jpeg": img_60,
  "1-2/옥미수.jpeg": img_61,
  "1-2/우황.jpeg": img_62,
  "1-2/욱리인.jpeg": img_63,
  "1-2/웅담.jpeg": img_64,
  "1-2/원화.jpeg": img_65,
  "1-2/위령선.jpeg": img_66,
  "1-2/위릉채.jpeg": img_67,
  "1-2/육계.jpeg": img_68,
  "1-2/은시호.jpeg": img_69,
  "1-2/의이인.jpeg": img_70,
  "1-2/인동등.jpeg": img_71,
  "1-2/인진호.jpeg": img_72,
  "1-2/자화지정.jpeg": img_73,
  "1-2/잠사.jpeg": img_74,
  "1-2/저령.jpeg": img_75,
  "1-2/적소두.jpeg": img_76,
  "1-2/정향.jpeg": img_77,
  "1-2/조휴.jpeg": img_78,
  "1-2/지각.jpeg": img_79,
  "1-2/지골피.jpeg": img_80,
  "1-2/지부자.jpeg": img_81,
  "1-2/지실.jpeg": img_82,
  "1-2/진교.jpeg": img_83,
  "1-2/진피.jpeg": img_84,
  "1-2/진피2.jpeg": img_85,
  "1-2/차전자.jpeg": img_86,
  "1-2/창출.jpeg": img_87,
  "1-2/천련자.jpeg": img_88,
  "1-2/천오두.jpeg": img_89,
  "1-2/청대.jpeg": img_90,
  "1-2/청목향.jpeg": img_91,
  "1-2/청피.jpeg": img_92,
  "1-2/청호.jpeg": img_93,
  "1-2/초과.jpeg": img_94,
  "1-2/초두구.jpeg": img_95,
  "1-2/초오.jpeg": img_96,
  "1-2/촉초.jpeg": img_97,
  "1-2/취오동.jpeg": img_98,
  "1-2/침향.jpeg": img_99,
  "1-2/택사.jpeg": img_100,
  "1-2/토목향.jpeg": img_101,
  "1-2/토복령.jpeg": img_102,
  "1-2/파두.jpeg": img_103,
  "1-2/판람근.jpeg": img_104,
  "1-2/패란.jpeg": img_105,
  "1-2/패장.jpeg": img_106,
  "1-2/편축.jpeg": img_107,
  "1-2/포공영.jpeg": img_108,
  "1-2/필발.jpeg": img_109,
  "1-2/필징가.jpeg": img_110,
  "1-2/해금사.jpeg": img_111,
  "1-2/해동피.jpeg": img_112,
  "1-2/해백.jpeg": img_113,
  "1-2/향부자.jpeg": img_114,
  "1-2/호초.jpeg": img_115,
  "1-2/호황련.jpeg": img_116,
  "1-2/화마인.jpeg": img_117,
  "1-2/활석.jpeg": img_118,
  "1-2/후박.jpeg": img_119,
  "1-2/희렴초.jpeg": img_120,
  "2-1/강황.jpeg": img_121,
  "2-1/건칠.jpeg": img_122,
  "2-1/계내금.jpeg": img_123,
  "2-1/계혈등.jpeg": img_124,
  "2-1/고련피.jpeg": img_125,
  "2-1/곡아.jpeg": img_126,
  "2-1/곤포.jpeg": img_127,
  "2-1/과루.jpeg": img_128,
  "2-1/관동화.jpeg": img_129,
  "2-1/관중.jpeg": img_130,
  "2-1/괴화.jpeg": img_131,
  "2-1/권백.jpeg": img_132,
  "2-1/길경.jpeg": img_133,
  "2-1/내복자.jpeg": img_134,
  "2-1/뇌환.jpeg": img_135,
  "2-1/능소화.jpeg": img_136,
  "2-1/단삼.jpeg": img_137,
  "2-1/대계.jpeg": img_138,
  "2-1/도인.jpeg": img_139,
  "2-1/동과자.jpeg": img_140,
  "2-1/마두령.jpeg": img_141,
  "2-1/맥아.jpeg": img_142,
  "2-1/몰약.jpeg": img_143,
  "2-1/무이.jpeg": img_144,
  "2-1/반대해.jpeg": img_145,
  "2-1/반하.jpeg": img_146,
  "2-1/백개자.jpeg": img_147,
  "2-1/백과.jpeg": img_148,
  "2-1/백급.jpeg": img_149,
  "2-1/백모근.jpeg": img_150,
  "2-1/백부근.jpeg": img_151,
  "2-1/백부자.jpeg": img_152,
  "2-1/백자인.jpeg": img_153,
  "2-1/백전.jpeg": img_154,
  "2-1/비자.jpeg": img_155,
  "2-1/비파엽.jpeg": img_156,
  "2-1/빈랑자.jpeg": img_157,
  "2-1/사군자.jpeg": img_158,
  "2-1/산사.jpeg": img_159,
  "2-1/산조인.jpeg": img_160,
  "2-1/삼릉.jpeg": img_161,
  "2-1/삼칠.jpeg": img_162,
  "2-1/상백피.jpeg": img_163,
  "2-1/선복화.jpeg": img_164,
  "2-1/소계.jpeg": img_165,
  "2-1/소목.jpeg": img_166,
  "2-1/소자.jpeg": img_167,
  "2-1/수질.jpeg": img_168,
  "2-1/신곡.jpeg": img_169,
  "2-1/아출.jpeg": img_170,
  "2-1/애엽.jpeg": img_171,
  "2-1/야교등.jpeg": img_172,
  "2-1/양제근.jpeg": img_173,
  "2-1/영지.jpeg": img_174,
  "2-1/오령지.jpeg": img_175,
  "2-1/왕불류행.jpeg": img_176,
  "2-1/용골.jpeg": img_177,
  "2-1/용아초.jpeg": img_178,
  "2-1/우슬.jpeg": img_179,
  "2-1/우절.jpeg": img_180,
  "2-1/울금.jpeg": img_181,
  "2-1/원지.jpeg": img_182,
  "2-1/유향.jpeg": img_183,
  "2-1/익모초.jpeg": img_184,
  "2-1/자석.jpeg": img_185,
  "2-1/자연동.jpeg": img_186,
  "2-1/자완.jpeg": img_187,
  "2-1/자충.jpeg": img_188,
  "2-1/전호.jpeg": img_189,
  "2-1/절패모.jpeg": img_190,
  "2-1/정력자.jpeg": img_191,
  "2-1/조각자.jpeg": img_192,
  "2-1/조협.jpeg": img_193,
  "2-1/종려피.jpeg": img_194,
  "2-1/주사.jpeg": img_195,
  "2-1/죽력.jpeg": img_196,
  "2-1/죽여.jpeg": img_197,
  "2-1/지유.jpeg": img_198,
  "2-1/천궁.jpeg": img_199,
  "2-1/천남성.jpeg": img_200,
  "2-1/천산갑.jpeg": img_201,
  "2-1/천축황.jpeg": img_202,
  "2-1/천패모.jpeg": img_203,
  "2-1/청몽석.jpeg": img_204,
  "2-1/충위자, 충울자.jpeg": img_205,
  "2-1/측백엽.jpeg": img_206,
  "2-1/택란.jpeg": img_207,
  "2-1/포황.jpeg": img_208,
  "2-1/학슬.jpeg": img_209,
  "2-1/합환피.jpeg": img_210,
  "2-1/해조.jpeg": img_211,
  "2-1/행인.jpeg": img_212,
  "2-1/현호색.jpeg": img_213,
  "2-1/혈갈.jpeg": img_214,
  "2-1/호박.jpeg": img_215,
  "2-1/호장근.jpeg": img_216,
  "2-1/홍화.jpeg": img_217,
  "2-2/가자.jpeg": img_218,
  "2-2/감초.jpeg": img_219,
  "2-2/검실.jpeg": img_220,
  "2-2/결명자.jpeg": img_221,
  "2-2/경분.jpeg": img_222,
  "2-2/골쇄보.jpeg": img_223,
  "2-2/과체.jpeg": img_224,
  "2-2/구기자.jpeg": img_225,
  "2-2/구인.jpeg": img_226,
  "2-2/구자.jpeg": img_227,
  "2-2/구척.jpeg": img_228,
  "2-2/구판.jpeg": img_229,
  "2-2/금앵자.jpeg": img_230,
  "2-2/나도근.jpeg": img_231,
  "2-2/노감석.jpeg": img_232,
  "2-2/노봉방.jpeg": img_233,
  "2-2/녹각.jpeg": img_234,
  "2-2/녹각교.jpeg": img_235,
  "2-2/녹각상.jpeg": img_236,
  "2-2/녹용.jpeg": img_237,
  "2-2/담반.jpeg": img_238,
  "2-2/당귀.jpeg": img_239,
  "2-2/당삼.jpeg": img_240,
  "2-2/대자석.jpeg": img_241,
  "2-2/대조.jpeg": img_242,
  "2-2/대풍자.jpeg": img_243,
  "2-2/동충화초.jpeg": img_244,
  "2-2/두충.jpeg": img_245,
  "2-2/마황근.jpeg": img_246,
  "2-2/맥문동.jpeg": img_247,
  "2-2/모려.jpeg": img_248,
  "2-2/목근피.jpeg": img_249,
  "2-2/반묘.jpeg": img_250,
  "2-2/백강잠.jpeg": img_251,
  "2-2/백반.jpeg": img_252,
  "2-2/백작약.jpeg": img_253,
  "2-2/백질려.jpeg": img_254,
  "2-2/백출.jpeg": img_255,
  "2-2/백편두.jpeg": img_256,
  "2-2/백합.jpeg": img_257,
  "2-2/별갑.jpeg": img_258,
  "2-2/보골지.jpeg": img_259,
  "2-2/복분자.jpeg": img_260,
  "2-2/봉밀.jpeg": img_261,
  "2-2/부소맥.jpeg": img_262,
  "2-2/붕사.jpeg": img_263,
  "2-2/비석.jpeg": img_264,
  "2-2/빙편.jpeg": img_265,
  "2-2/사삼.jpeg": img_266,
  "2-2/사상자.jpeg": img_267,
  "2-2/사원질려.jpeg": img_268,
  "2-2/사향.jpeg": img_269,
  "2-2/산수유.jpeg": img_270,
  "2-2/산약.jpeg": img_271,
  "2-2/상산.jpeg": img_272,
  "2-2/상심자.jpeg": img_273,
  "2-2/상표초.jpeg": img_274,
  "2-2/석결명.jpeg": img_275,
  "2-2/석곡.jpeg": img_276,
  "2-2/석류피.jpeg": img_277,
  "2-2/석창포.jpeg": img_278,
  "2-2/선모.jpeg": img_279,
  "2-2/섬수.jpeg": img_280,
  "2-2/소합향.jpeg": img_281,
  "2-2/속단.jpeg": img_282,
  "2-2/쇄양.jpeg": img_283,
  "2-2/숙지황.jpeg": img_284,
  "2-2/아교.jpeg": img_285,
  "2-2/안식향.jpeg": img_286,
  "2-2/양기석.jpeg": img_287,
  "2-2/여로.jpeg": img_288,
  "2-2/여정자.jpeg": img_289,
  "2-2/연자육.jpeg": img_290,
  "2-2/연탄.jpeg": img_291,
  "2-2/영양각.jpeg": img_292,
  "2-2/오공.jpeg": img_293,
  "2-2/오매.jpeg": img_294,
  "2-2/오미자.jpeg": img_295,
  "2-2/오배자.jpeg": img_296,
  "2-2/옥죽.jpeg": img_297,
  "2-2/용안육.jpeg": img_298,
  "2-2/우여량.jpeg": img_299,
  "2-2/웅황.jpeg": img_300,
  "2-2/유황.jpeg": img_301,
  "2-2/육두구.jpeg": img_302,
  "2-2/육종용.jpeg": img_303,
  "2-2/음양곽.jpeg": img_304,
  "2-2/익지인.jpeg": img_305,
  "2-2/인삼.jpeg": img_306,
  "2-2/자하거.jpeg": img_307,
  "2-2/장뇌.jpeg": img_308,
  "2-2/저실자.jpeg": img_309,
  "2-2/적석지.jpeg": img_310,
  "2-2/전갈.jpeg": img_311,
  "2-2/조구등.jpeg": img_312,
  "2-2/진주.jpeg": img_313,
  "2-2/천마.jpeg": img_314,
  "2-2/천문동.jpeg": img_315,
  "2-2/춘피.jpeg": img_316,
  "2-2/토사자.jpeg": img_317,
  "2-2/파극천.jpeg": img_318,
  "2-2/하수오.jpeg": img_319,
  "2-2/한련초.jpeg": img_320,
  "2-2/합개.jpeg": img_321,
  "2-2/해구신.jpeg": img_322,
  "2-2/해마.jpeg": img_323,
  "2-2/해표초.jpeg": img_324,
  "2-2/호도인.jpeg": img_325,
  "2-2/호로퍄.jpeg": img_326,
  "2-2/황기.jpeg": img_327,
  "2-2/황정.jpeg": img_328,
  "2-2/흑지마.jpeg": img_329,
};
