// scripts/generateImageList.js
const fs = require('fs');
const path = require('path');

const imagesBaseDir = path.join(__dirname, '../public/images');
const publicDir = path.join(__dirname, '../public');
const utilsDir = path.join(__dirname, '../utils');

// Ensure utils directory exists
if (!fs.existsSync(utilsDir)) {
    fs.mkdirSync(utilsDir);
}

const dirMapping = {
    '1-2': 'imageList-1-1.json',
    '2-1': 'imageList-1-2.json',
    '2-2': 'imageList-1-3.json'
};

// public/images 안의 모든 폴더를 읽음
const subDirs = fs.readdirSync(imagesBaseDir).filter(dir =>
    fs.statSync(path.join(imagesBaseDir, dir)).isDirectory()
);

// 기존 imageList.json 삭제 (if exists)
const oldJsonPath = path.join(publicDir, 'imageList.json');
if (fs.existsSync(oldJsonPath)) {
    fs.unlinkSync(oldJsonPath);
    console.log('🗑️  기존 imageList.json 삭제 완료');
}

let allImageImports = [];
let allImageMapEntries = [];
let globalImageIndex = 0;

// 각 폴더별로 별도의 JSON 파일을 생성하고, 통합 TS 맵을 위한 데이터 수집
subDirs.forEach(dir => {
    const jsonFileName = dirMapping[dir];
    if (!jsonFileName) {
        console.log(`⚠️ ${dir}에 대한 매핑이 없어 건너뜁니다.`);
        return;
    }

    const imageFiles = fs.readdirSync(path.join(imagesBaseDir, dir))
        .filter(f => /\.(jpe?g|png)$/i.test(f));

    let imagePaths = [];
    imageFiles.forEach(oldName => {
        const nfcName = oldName.normalize('NFC');
        const oldPath = path.join(imagesBaseDir, dir, oldName);
        const newPath = path.join(imagesBaseDir, dir, nfcName);

        if (oldName !== nfcName) {
            fs.renameSync(oldPath, newPath);
            console.log(`🔄 rename: ${oldName} → ${nfcName}`);
        }

        // dir/image.jpeg
        const relativePath = `${dir}/${nfcName}`;
        imagePaths.push(relativePath);

        // For TS generation
        // Use a simple counter to avoid naming collisions with non-ASCII characters
        const safeName = `img_${globalImageIndex++}`;

        // Import path relative to utils/imageMap.ts -> ../public/images/...
        allImageImports.push(`import ${safeName} from "../public/images/${relativePath}";`);
        allImageMapEntries.push(`  "${relativePath}": ${safeName},`);
    });

    imagePaths.sort();

    const jsonPath = path.join(publicDir, jsonFileName);

    // JSON 작성 (기존 호환성 유지)
    fs.writeFileSync(jsonPath, JSON.stringify(imagePaths, null, 2), 'utf-8');
});

// Generate utils/imageMap.ts
const tsContent = `// This file is automatically generated by scripts/generateImageList.js
// Do not edit this file manually.

${allImageImports.join('\n')}

export const imageMap: Record<string, any> = {
${allImageMapEntries.join('\n')}
};
`;

const tsPath = path.join(utilsDir, 'imageMap.ts');
fs.writeFileSync(tsPath, tsContent, 'utf-8');
console.log(`✅ utils/imageMap.ts 생성 완료 (${allImageImports.length} images)`);